Allow to pass multiple upstream URIs

diff --git a/msync b/msync
--- a/msync
+++ b/msync
@@ -36,7 +36,7 @@ rsync_cmd() {
     cmd+=(--times --perms)
     cmd+=(--links --safe-links --hard-links --sparse)
     cmd+=(--delete-delay --delay-updates --temp-dir="${temp_dir}")
-    cmd+=(--timeout=300 --contimeout=30)
+    cmd+=(--contimeout=60 --timeout=600)
 
     test -z "$verbose" || cmd+=(--verbose --progress --stats)
 
@@ -47,7 +47,15 @@ rsync_cmd() {
 
     verbose "About to run:" "${cmd[@]}"
     verbose ""
-    "${cmd[@]}"
+
+    if [ "$verbose" ]; then
+        "${cmd[@]}"
+    else
+        "${cmd[@]}" 2>&1 \
+        | grep -Ev '^file has vanished:' \
+        | grep -Ev '^rsync warning: some files vanished before they could be transferred'
+    fi
+
     exit_status=$?
     verbose ""
     verbose "rsync exited with $exit_status"
@@ -55,7 +63,11 @@ rsync_cmd() {
 }
 
 verbose() {
-    test -z "$verbose" || echo >&2 "$@"
+    test -z "$verbose" || warn "$@"
+}
+
+warn() {
+    echo >&2 "$@"
 }
 
 # DEFAULT OPTIONS
@@ -63,13 +75,13 @@ verbose() {
 verbose=""
 tty -s && verbose=1
 
-rsync_uri=""
 destination_path=""
 last_update_url=""
 last_update_sync=""
 warning_timeout=300
 random_delay=1
 
+declare -a rsync_uris
 declare -a rsync_options
 
 # PARSE OPTIONS
@@ -79,7 +91,7 @@ declare -a rsync_options
 while true; do
     case ${1:-} in
     "") break;;
-    rsync://*) rsync_uri=$1; shift;;
+    rsync://*) rsync_uris+=("$1"); shift;;
     --verbose) verbose=1; shift;;
     --quiet) verbose=""; shift;;
     --dry-run) rsync_options+=("$1"); shift;;
@@ -89,7 +101,7 @@ while true; do
     --random-delay) shift; random_delay=$1; shift;;
     --warning-timeout) shift; warning_timeout=$1; shift;;
     --rsync-options) shift; rsync_options+=("$1"); shift;;
-    *) destination_path=$(readlink -f "$1"); shift;;
+    *) destination_path=$(readlink -m "$1"); shift;;
     esac
 done
 
@@ -105,7 +117,7 @@ temp_dir="/tmp/msync-${id}"
 lock_file="/tmp/msync-${id}.lck"
 
 if [[ "$last_update_sync" && -z "$last_update_url" ]]; then
-     echo >&2 "--last-update-sync requires --last-update-url to be set."
+     warn "--last-update-sync requires --last-update-url to be set."
      exit 1
 fi
 
@@ -114,10 +126,10 @@ verbose "Verbose mode is on"
 # SET UP FOR SYNC
 
 exec 9>"${lock_file}"
-flock -n 9 || { verbose "${lock_file} present. Exiting."; exit 0; }
+flock -n 9 || { verbose "${lock_file} present, exiting."; exit 0; }
 
 exit_handler() {
-    [ $SECONDS -le "$warning_timeout" ] || echo >&2 "Warning: msync took $SECONDS s"
+    [ $SECONDS -le "$warning_timeout" ] || warn "msync took $SECONDS s"
 
     [ ! -d $temp_dir ] || rmdir $temp_dir
     rm $lock_file
@@ -134,6 +146,22 @@ tty -s || {
     warning_timeout=$((warning_timeout + delay))
     sleep $delay
 }
+
+rsync_uri=""
+for uri in "${rsync_uris[@]}"; do
+    if rsync --no-motd --contimeout=10 --timeout=30 "$uri" >/dev/null; then
+        rsync_uri=$uri
+        verbose "${uri} is up, using it as upstream"
+        break
+    else
+        warn "${uri} is down, trying next upstream..."
+    fi
+done
+
+if [ -z "$rsync_uri" ]; then
+    warn "Could not find any valid upstreams, aborting."
+    exit 1
+fi
 
 if [ "$last_update_url" ]; then
     last_update_file="$destination_path/${last_update_url##*/}"
@@ -165,8 +193,8 @@ fi
 
 exit_status=$?
 
-if [[ -z "$verbose" || $exit_status -ne 0 && $exit_status -ne 24 ]]; then
-    echo -n "$output"
+if [[ -z "$verbose" && $exit_status -ne 0 && $exit_status -ne 24 ]]; then
+    warn "$output"
 fi
 
 exit $exit_status
